export const MAX_RASTER_SOURCE_BYTES = 12 * 1024 * 1024;
export const MAX_RASTER_WIDTH_PX = 10_000;
export const MAX_RASTER_HEIGHT_PX = 10_000;
export const MAX_RASTER_DECODED_PIXELS = 20_000_000;
export const MAX_RASTER_DECODED_BYTES = MAX_RASTER_DECODED_PIXELS * 4;
export const MAX_RASTER_TRACE_PIXELS = 4_000_000;
export const MAX_RASTER_TRACE_EDGES = 800_000;
export const MAX_RASTER_TRACE_POINTS = 200_000;
export const MAX_RASTER_PREVIEW_DIMENSION_PX = 800;
export const MAX_RASTER_PROCESSING_TIME_MS = 30_000;

export const GRID_TRACE_ENGINE_ID = "laserx-grid-trace";
export const GRID_TRACE_ENGINE_VERSION = "1.0.0";
